services:
  postgres:
    image: postgres:16
    container_name: arduino-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql/data
    restart: always
  
  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: port-forwarder-arduino-postgres
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:arduino-postgres:5432
    ports:
     - "127.0.0.1:5432:5432"

  grafana:
    image: grafana/grafana:13.0.0-24058232110
    container_name: grafana
    ports:
     - "3000:3000"
    volumes:
     - ${PROJECT_ROOT}/out/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

